### ISSUE TITLE
gnome-shell crashes when this extension is enabled.

### ISSUE THREAD

**Issue by wastee** [ubuntu/gnome-shell-extension-appindicator#504]
```
gnome-shell 1:45.4
gnome-shell-extensions 45.2
mutter 45.4
[element](url) 0.46.6
```

## Steps

1. Open `element`
2. gnome-shell crash
3. return to GDM

If i disable this extension, `[Element](https://kushview.net/element/)` will open successfully.

## logs

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=5, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007e0a72cab393 in __pthread_kill_internal (signo=5, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007e0a72c5a6c8 in __GI_raise (sig=sig@entry=5) at ../sysdeps/posix/raise.c:26
#3  0x00005ab7b2353109 in dump_gjs_stack_on_signal_handler (signo=5) at ../gnome-shell/src/main.c:467
#4  0x00007e0a72c5a770 in <signal handler called> () at /usr/lib/libc.so.6
#5  g_log_structured_array (log_level=log_level@entry=G_LOG_LEVEL_ERROR, fields=fields@entry=0x7fff335c15e0, n_fields=4)
    at ../glib/glib/gmessages.c:556
#6  0x00007e0a734da5a3 in g_log_default_handler
    (log_domain=log_domain@entry=0x7e0a73088023 "Mtk", log_level=log_level@entry=6, message=message@entry=0x5ab7b5783a70 "Received an X Window System error.\nThis probably reflects a bug in the program.\nThe error was 'BadWindow (invalid Window parameter)'.\n  (Details: serial 444 error_code 3 request_code 2 (core protocol)"..., unused_data=unused_data@entry=0x0)
    at ../glib/glib/gmessages.c:3284
#7  0x00007e0a734db455 in g_logv
    (log_domain=0x7e0a73088023 "Mtk", log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7fff335c1730)
    at ../glib/glib/gmessages.c:1392
#8  0x00007e0a734db724 in g_log
    (log_domain=log_domain@entry=0x7e0a73088023 "Mtk", log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x7e0a730880d0 "Received an X Window System error.\nThis probably reflects a bug in the program.\nThe error was '%s'.\n  (Details: serial %ld error_code %d request_code %d (%s) minor_code %d)\n  (Note to programmers: nor"...)
    at ../glib/glib/gmessages.c:1461
#9  0x00007e0a7308725f in display_error_event (error=0x7fff335c18b0, xdisplay=0x5ab7bbccaf40)
    at ../mutter/mtk/mtk/mtk-x11-errors.c:116
#10 mtk_x_error (xdisplay=0x5ab7bbccaf40, error=0x7fff335c18b0) at ../mutter/mtk/mtk/mtk-x11-errors.c:139
#11 0x00007e0a729c774c in _XError (dpy=dpy@entry=0x5ab7bbccaf40, rep=rep@entry=0x5ab7b65f7630)
    at /usr/src/debug/libx11/libX11-1.8.7/src/XlibInt.c:1503
#12 0x00007e0a729c7858 in handle_error (dpy=0x5ab7bbccaf40, err=0x5ab7b65f7630, in_XReply=<optimized out>)
    at /usr/src/debug/libx11/libX11-1.8.7/src/xcb_io.c:211
#13 0x00007e0a729c7915 in handle_response
    (dpy=dpy@entry=0x5ab7bbccaf40, response=0x5ab7b65f7630, in_XReply=in_XReply@entry=1)
    at /usr/src/debug/libx11/libX11-1.8.7/src/xcb_io.c:403
#14 0x00007e0a729c92fd in _XReply (dpy=0x5ab7bbccaf40, rep=0x7fff335c1ac0, extra=0, discard=0)
    at /usr/src/debug/libx11/libX11-1.8.7/src/xcb_io.c:722
#15 0x00007e0a729aa0f4 in XGetWindowProperty
    (dpy=0x5ab7bbccaf40, w=12582939, property=334, offset=offset@entry=0, length=length@entry=32, delete=delete@entry=0, req_type=33, actual_type=0x7fff335c1bb8, actual_format=0x7fff335c1b9c, nitems=0x7fff335c1bb0, bytesafter=0x7fff335c1ba8, prop=0x7fff335c1ba0) at /usr/src/debug/libx11/libX11-1.8.7/src/GetProp.c:69
#16 0x00007e0a72f0f3e3 in handle_other_xevent
    (x11_display=x11_display@entry=0x5ab7bbcf1830, event=event@entry=0x7fff335c1f40) at ../mutter/src/x11/events.c:1460

#17 0x00007e0a72f11618 in meta_x11_display_handle_xevent (event=0x7fff335c1f40, x11_display=<optimized out>)
    at ../mutter/src/x11/events.c:1931
#18 xevent_func (xevent=0x7fff335c1f40, data=<optimized out>) at ../mutter/src/x11/events.c:1971



#19 0x00007e0a72f1580e in meta_x11_event_source_dispatch
    (source=0x5ab7bbcfed00, callback=0x7e0a72f10d10 <xevent_func>, user_data=0x5ab7bbcf1830)
    at ../mutter/src/x11/meta-x11-event-source.c:62
#20 0x00007e0a734d2f69 in g_main_dispatch (context=0x5ab7b3fa7f60) at ../glib/glib/gmain.c:3476
#21 0x00007e0a735313a7 in g_main_context_dispatch_unlocked (context=0x5ab7b3fa7f60) at ../glib/glib/gmain.c:4284
#22 g_main_context_iterate_unlocked.isra.0
    (context=0x5ab7b3fa7f60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4349
#23 0x00007e0a734d3b97 in g_main_loop_run (loop=0x5ab7b48b2960) at ../glib/glib/gmain.c:4551
#24 0x00007e0a72ec441b in meta_context_run_main_loop (context=<optimized out>, error=0x7fff335c2570)
    at ../mutter/src/core/meta-context.c:514
#25 0x00007e0a723c7596 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#26 0x00007e0a723c400e in ffi_call_int
    (cif=cif@entry=0x5ab7b4995fd0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#27 0x00007e0a723c6bd3 in ffi_call
    (cif=0x5ab7b4995fd0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#28 0x00007e0a7335bfa7 in Gjs::Function::invoke
    (this=0x5ab7b4995fb0, context=context@entry=0x5ab7b3ff9150, args=..., this_obj=..., r_value=r_value@entry=0x0)
    at ../gjs/gi/function.cpp:1058
#29 0x00007e0a73366ba8 in Gjs::Function::call (context=0x5ab7b3ff9150, js_argc=<optimized out>, vp=<optimized out>)
    at ../gjs/gi/function.cpp:1236
#30 0x00007e0a7195dd28 in CallJSNative
    (cx=0x5ab7b3ff9150, native=0x7e0a73366ac0 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, reason=js::CallReason::Call, args=...) at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:486
#31 js::InternalCallOrConstruct (cx=0x5ab7b3ff9150, args=..., construct=<optimized out>, reason=js::CallReason::Call)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:566
#32 0x00007e0a715db786 in InternalCall (cx=0x5ab7b3ff9150, args=..., reason=<optimized out>)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:647
#33 js::CallFromStack (cx=0x5ab7b3ff9150, args=..., reason=<optimized out>)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:652
#34 js::Interpret (cx=0x5ab7b3ff9150, state=...) at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:3395
#35 0x00007e0a715d55bf in MaybeEnterInterpreterTrampoline (cx=0x5ab7b3ff9150, state=...)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:400
#36 js::RunScript (cx=0x5ab7b3ff9150, state=...) at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:458
#37 js::InternalCallOrConstruct (cx=0x5ab7b3ff9150, args=..., construct=js::NO_CONSTRUCT, reason=<optimized out>)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:612
#38 InternalCall (cx=0x5ab7b3ff9150, args=..., reason=<optimized out>)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:647
#39 js::Call (cx=0x5ab7b3ff9150, fval=..., thisv=..., args=..., rval=..., reason=<optimized out>)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/Interpreter.cpp:679
#40 0x00007e0a71ab75d3 in JS::Call (cx=0x5ab7b3ff9150, thisv=..., fval=..., args=..., rval=...)
    at /usr/src/debug/js115/firefox-115.8.0/js/src/vm/CallAndConstruct.cpp:117
#41 0x00007e0a7339b552 in JS::Call (rval=..., args=..., funObj=..., thisv=..., cx=<optimized out>)
    at /usr/include/mozjs-115/js/RootingAPI.h:1219
#42 GjsContextPrivate::run_main_loop_hook (this=0x5ab7b3fefb90) at ../gjs/gjs/context.cpp:1428
#43 0x00007e0a733a310f in GjsContextPrivate::eval_module
    (error=0x7fff335c3010, exit_status_p=0x7fff335c300b "", identifier=0x5ab7b48b4f20 "resource:///org/gnome/shell/ui/init.js", this=0x5ab7b3fefb90) at ../gjs/gjs/context.cpp:1545
#44 gjs_context_eval_module
    (js_context=<optimized out>, identifier=0x5ab7b48b4f20 "resource:///org/gnome/shell/ui/init.js", exit_code=0x7fff335c300b "", error=0x7fff335c3010) at ../gjs/gjs/context.cpp:1324
#45 0x00007e0a733a3411 in gjs_context_eval_module_file
    (js_context=js_context@entry=0x5ab7b3fefd10, filename=filename@entry=0x5ab7b2354640 "resource:///org/gnome/shell/ui/init.js", exit_status_p=exit_status_p@entry=0x7fff335c300b "", error=error@entry=0x7fff335c3010)
    at ../gjs/gjs/context.cpp:1629
#46 0x00005ab7b235257f in main (argc=<optimized out>, argv=<optimized out>) at ../gnome-shell/src/main.c:708
```

--------

If there is anything you need to debug, please tell me.

**Comment by 3v1n0** [comment]
Try to run gnome shell with sync X events

**Comment by TJFOE** [comment]
> Try to run gnome shell with sync X events

Could you please explain this a little bit more...? I have exactly the same problem as bass9030...

**Comment by TJFOE** [comment]
I get the crash too, if I install it only from the official repository (Manjaro)...

**Comment by TJFOE** [comment]
Ahhh ... there is a bug report. [Linking](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7447) to this issue.
